# Generated by Django 2.2.6 on 2019-11-19 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('audit', '0004_auto_20191119_0039'),
        ('classes', '0003_class_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='NatSciRequirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creditRequirement', models.IntegerField()),
                ('currentCredit', models.IntegerField()),
                ('auditId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audit.Audit')),
                ('classes', models.ManyToManyField(related_name='classes', to='classes.Class')),
            ],
        ),
    ]
