# Generated by Django 2.2.6 on 2019-10-31 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='major',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
    ]
