# Generated by Django 2.2.8 on 2020-01-15 03:04

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.FileField(upload_to=users.models.update_filename, validators=[users.models.validate_file]),
        ),
    ]
