# Generated by Django 2.2.8 on 2020-01-10 03:28

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200109_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.FileField(upload_to='documents/', validators=[users.models.FileValidator(content_types=('application/pdf',))]),
        ),
    ]
