# Generated by Django 2.2.8 on 2020-01-10 03:53

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200109_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.FileField(upload_to=users.models.update_filename, validators=[users.models.FileValidator(content_types=('application/pdf',))]),
        ),
    ]
