# Generated by Django 2.2.8 on 2020-01-12 20:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('useraudits', '0002_userauditentry_credits'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAuditInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gpa', models.CharField(max_length=10)),
                ('progress', models.CharField(max_length=10)),
                ('attempted', models.CharField(max_length=10)),
                ('earned', models.CharField(max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userauditinfo', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
