# Generated by Django 2.2.8 on 2020-01-15 05:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0008_merge_20191201_2306'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('useraudits', '0003_userauditinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userauditinfo',
            name='gpa',
        ),
        migrations.AddField(
            model_name='userauditentry',
            name='transfer',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='userauditinfo',
            name='gpa_complete',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='userauditinfo',
            name='gpa_cu',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='userauditinfo',
            name='gpa_transfer',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='userauditinfo',
            name='num_cu_courses',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='userauditinfo',
            name='num_transfers',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='userauditentry',
            name='grade',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='userauditentry',
            name='semester',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='userauditentry',
            name='year',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='userauditinfo',
            name='attempted',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='userauditinfo',
            name='earned',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='userauditinfo',
            name='progress',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.CreateModel(
            name='UserAuditTransferEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(blank=True, max_length=10)),
                ('semester', models.CharField(blank=True, max_length=10)),
                ('level', models.CharField(blank=True, max_length=10)),
                ('grade', models.CharField(blank=True, max_length=10)),
                ('credits', models.CharField(blank=True, max_length=10)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usertransfers', to='classes.Class')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usertransfers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
