# Generated by Django 2.2.8 on 2020-01-15 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('useraudits', '0004_auto_20200114_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraudittransferentry',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usertransfers', to='classes.Department'),
        ),
    ]
