# Generated by Django 2.2.8 on 2020-01-15 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraudits', '0005_auto_20200115_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userauditentry',
            name='credits',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='userauditinfo',
            name='attempted',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userauditinfo',
            name='earned',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userauditinfo',
            name='gpa_complete',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='userauditinfo',
            name='gpa_cu',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='userauditinfo',
            name='gpa_transfer',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='userauditinfo',
            name='num_cu_courses',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userauditinfo',
            name='num_transfers',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userauditinfo',
            name='progress',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='useraudittransferentry',
            name='credits',
            field=models.FloatField(default=0.0),
        ),
    ]
