# Generated by Django 2.2.8 on 2020-01-15 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraudits', '0006_auto_20200115_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='userauditinfo',
            name='transfer_credits',
            field=models.FloatField(default=0.0),
        ),
    ]
