# Generated by Django 2.2.8 on 2020-01-15 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraudits', '0007_userauditinfo_transfer_credits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userauditinfo',
            name='attempted',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='userauditinfo',
            name='earned',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='userauditinfo',
            name='progress',
            field=models.FloatField(default=0.0),
        ),
    ]
