language: python
    
    python: 
        - "3.6"

    services:
        - postgresql

    env:
        -DJANGO=2.2.6 DB=postgresql

    install:
        - pip install -r requirements/base.txt
    
    before_script:
        - psql -c 'create database travis_ci_test;' -U postgres

    script:
        - python manage.py test
