# Generated by Django 2.2.6 on 2019-10-26 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='class_component',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='class',
            name='credit',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='class',
            name='session',
            field=models.CharField(max_length=5),
        ),
    ]
