# Generated by Django 2.2.6 on 2019-11-07 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0001_initial'),
        ('classes', '0002_auto_20191026_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='schedule',
            field=models.ManyToManyField(related_name='classes', to='schedules.Schedule'),
        ),
    ]
