# Generated by Django 2.2.6 on 2019-10-26 20:41

from django.db import migrations
from django.db import transaction

def PopulateClasses(app, schema_editor):
    Class = app.get_model("classes", "Class")

    f = open('classes/migrations/class_schedule.csv', 'r')

    failures = 0

    for line in f:
        course = Class()
        # remove newline char at end and replace temporary semicolons back to commas
        data = [x.replace(";", ",") for x in line[:len(line) - 1].split(",")]
        course.department = data[0]
        course.course_subject = data[1]
        course.section_number = data[2]
        course.session = data[3]
        course.class_number = data[4]
        course.credit = data[5]
        course.course_title = data[6]
        course.class_component = data[7]
        course.start_time = data[8]
        course.end_time = data[9]
        course.days = data[10]
        course.building_room = data[11]
        course.instructor_name = data[12]
        course.max_enrollment = data[13]
        course.campus = data[14]
        try:
            with transaction.atomic():
                course.save()
        except:
            print(data)
            failures += 1
    print("Failed to add" , failures, "classes")

class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_auto_20191026_2041'),
    ]

    operations = [
        migrations.RunPython(PopulateClasses)
    ]
