# Generated by Django 2.2.6 on 2019-11-20 03:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0001_initial'),
        ('classes', '0004_auto_20191115_0904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='building_room',
        ),
        migrations.RemoveField(
            model_name='class',
            name='campus',
        ),
        migrations.RemoveField(
            model_name='class',
            name='class_component',
        ),
        migrations.RemoveField(
            model_name='class',
            name='class_number',
        ),
        migrations.RemoveField(
            model_name='class',
            name='credit',
        ),
        migrations.RemoveField(
            model_name='class',
            name='days',
        ),
        migrations.RemoveField(
            model_name='class',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='class',
            name='instructor_name',
        ),
        migrations.RemoveField(
            model_name='class',
            name='max_enrollment',
        ),
        migrations.RemoveField(
            model_name='class',
            name='schedule',
        ),
        migrations.RemoveField(
            model_name='class',
            name='section_number',
        ),
        migrations.RemoveField(
            model_name='class',
            name='session',
        ),
        migrations.RemoveField(
            model_name='class',
            name='start_time',
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_number', models.CharField(max_length=5)),
                ('session', models.CharField(max_length=5)),
                ('class_number', models.IntegerField()),
                ('credit', models.CharField(max_length=5)),
                ('class_component', models.CharField(max_length=10)),
                ('start_time', models.CharField(blank=True, max_length=10, null=True)),
                ('end_time', models.CharField(blank=True, max_length=10, null=True)),
                ('days', models.CharField(blank=True, max_length=10, null=True)),
                ('building_room', models.CharField(blank=True, max_length=40, null=True)),
                ('instructor_name', models.CharField(blank=True, max_length=50, null=True)),
                ('max_enrollment', models.IntegerField()),
                ('campus', models.CharField(max_length=15)),
                ('parent_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='classes.Class')),
                ('schedule', models.ManyToManyField(related_name='classes', to='schedules.Schedule')),
            ],
        ),
    ]
