# Generated by Django 2.2.6 on 2019-11-21 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('completedclasses', '0001_initial'),
        ('classes', '0004_auto_20191115_0904'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='completed',
            field=models.ManyToManyField(related_name='completed', to='completedclasses.CompletedClasses'),
        ),
    ]
