# Generated by Django 2.2.6 on 2019-11-30 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fcq', '0001_initial'),
        ('classes', '0005_auto_20191119_2015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='instructor_name',
        ),
        migrations.AddField(
            model_name='section',
            name='professor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='fcq.Professor'),
        ),
        migrations.AlterField(
            model_name='section',
            name='parent_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='classes.Class'),
        ),
    ]
