# Generated by Django 2.2.6 on 2019-11-21 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0005_class_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='completed',
            field=models.ManyToManyField(related_name='classes', to='completedclasses.CompletedClasses'),
        ),
    ]
