# Generated by Django 2.2.6 on 2019-11-22 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0005_auto_20191119_2015'),
        ('classes', '0006_auto_20191121_0345'),
    ]

    operations = [
    ]
