# Generated by Django 2.2.6 on 2019-12-01 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0007_merge_20191122_1533'),
        ('classes', '0006_auto_20191130_0210'),
    ]

    operations = [
    ]
