# Generated by Django 2.2.6 on 2019-11-07 00:38

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FCQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('year', models.CharField(max_length=50)),
                ('semester', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=50)),
                ('course', models.CharField(max_length=50)),
                ('section', models.CharField(max_length=50)),
                ('courseTitle', models.CharField(max_length=200)),
                ('courseType', models.CharField(max_length=50)),
                ('level', models.CharField(max_length=50)),
                ('online', models.CharField(max_length=50)),
                ('size', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('mainDepartment', models.CharField(max_length=50)),
                ('numClasses', models.IntegerField()),
                ('avgClassSize', models.IntegerField()),
                ('avgInstRating', models.FloatField()),
                ('avgCourseRating', models.FloatField()),
                ('avgChallenge', models.FloatField()),
                ('courseList', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), size=None)),
                ('timesCourseTaught', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('courseRating', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None)),
                ('courseInstRating', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None)),
                ('courseChallenge', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None)),
                ('classIndex', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
            ],
        ),
    ]
