# Generated by Django 2.2.6 on 2019-11-04 01:01

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('mainDepartment', models.CharField(max_length=6)),
                ('numClasses', models.IntegerField(default=0)),
                ('avgClassSize', models.IntegerField(default=0)),
                ('avgInstRating', models.FloatField(default=0.0)),
                ('avgCourseRating', models.FloatField(default=0.0)),
                ('avgChallenge', models.FloatField(default=0.0)),
                ('courseList', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=8), size=models.IntegerField(default=0))),
                ('timesCourseTaught', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=1), size=models.IntegerField(default=0))),
                ('courseRating', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(default=0.0), size=models.IntegerField(default=0))),
                ('courseInstRating', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(default=0.0), size=models.IntegerField(default=0))),
                ('courseChallenge', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(default=0.0), size=models.IntegerField(default=0))),
                ('classIndex', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=models.IntegerField(default=0))),
            ],
        ),
    ]
