# Generated by Django 2.2.6 on 2019-11-27 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0005_auto_20191119_2015'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FCQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4)),
                ('semester', models.CharField(max_length=10)),
                ('section', models.CharField(max_length=4)),
                ('courseType', models.CharField(max_length=5)),
                ('online', models.CharField(max_length=1)),
                ('size', models.IntegerField(default=0)),
                ('numResponses', models.IntegerField(default=0)),
                ('challenge', models.FloatField(default=0.0)),
                ('learned', models.FloatField(default=0.0)),
                ('courseRating', models.FloatField(default=0.0)),
                ('profEffect', models.FloatField(default=0.0)),
                ('profRating', models.FloatField(default=0.0)),
                ('courseSD', models.FloatField(default=0.0)),
                ('profSD', models.FloatField(default=0.0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fcqs', to='classes.Class')),
                ('professor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fcqs', to='fcq.Professor')),
            ],
        ),
    ]
