# Generated by Django 2.2.6 on 2019-11-15 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fcq', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fcq',
            name='subject',
        ),
    ]
