# Generated by Django 2.2.6 on 2019-11-27 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fcq', '0003_auto_20191127_0844'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='fullName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
