# Generated by Django 2.2.6 on 2019-12-12 04:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classes', '0008_merge_20191201_2306'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Prerequisite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requiredNumber', models.IntegerField()),
                ('corequisite', models.BooleanField()),
                ('audit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='audit.Audit')),
                ('classes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='classes.Class')),
                ('possibleClasses', models.ManyToManyField(related_name='possibleClasses', to='classes.Class')),
            ],
        ),
        migrations.CreateModel(
            name='DegreeSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sectionName', models.CharField(max_length=40)),
                ('creditRequirement', models.IntegerField()),
                ('currentCredit', models.IntegerField()),
                ('appliedClasses', models.ManyToManyField(related_name='appliedClasses', to='classes.Class')),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audit.Audit')),
            ],
        ),
    ]
