# Generated by Django 2.2.6 on 2019-11-19 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_class_schedule'),
        ('audit', '0002_auto_20191118_0331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prerequisite',
            name='classId',
        ),
        migrations.AddField(
            model_name='audit',
            name='currentLowerHumnRequirement',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='audit',
            name='currentUpperHumnRequirement',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='audit',
            name='lowerHumnRequirement',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='audit',
            name='upperHumnRequierement',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prerequisite',
            name='classes',
            field=models.ManyToManyField(related_name='classes', to='classes.Class'),
        ),
    ]
