# Generated by Django 2.2.6 on 2019-11-19 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0003_auto_20191119_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prerequisite',
            name='classes',
            field=models.ManyToManyField(related_name='appliedClasses', to='classes.Class'),
        ),
    ]
