# Generated by Django 2.2.6 on 2019-11-19 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_class_schedule'),
        ('audit', '0004_auto_20191119_0039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audit',
            name='creditRequirement',
        ),
        migrations.RemoveField(
            model_name='audit',
            name='currentCredit',
        ),
        migrations.RemoveField(
            model_name='audit',
            name='currentLowerHumnRequirement',
        ),
        migrations.RemoveField(
            model_name='audit',
            name='currentMajorCredit',
        ),
        migrations.RemoveField(
            model_name='audit',
            name='currentUpperHumnRequirement',
        ),
        migrations.RemoveField(
            model_name='audit',
            name='lowerHumnRequirement',
        ),
        migrations.RemoveField(
            model_name='audit',
            name='majorRequirement',
        ),
        migrations.RemoveField(
            model_name='audit',
            name='upperHumnRequierement',
        ),
        migrations.AlterField(
            model_name='prerequisite',
            name='classes',
            field=models.ManyToManyField(related_name='classes', to='classes.Class'),
        ),
        migrations.CreateModel(
            name='DegreeSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sectionName', models.CharField(max_length=40)),
                ('creditRequirement', models.IntegerField()),
                ('currentCredit', models.IntegerField()),
                ('appliedClasses', models.ManyToManyField(related_name='appliedClasses', to='classes.Class')),
                ('auditId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audit.Audit')),
            ],
        ),
    ]
