# Generated by Django 2.2.6 on 2019-11-21 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0005_auto_20191119_0056'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompletedClass',
        ),
    ]
