# Generated by Django 2.2.6 on 2019-11-24 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0007_merge_20191122_1533'),
        ('audit', '0006_delete_completedclass'),
    ]

    operations = [
        migrations.AddField(
            model_name='prerequisite',
            name='corequisite',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='prerequisite',
            name='classes',
        ),
        migrations.AddField(
            model_name='prerequisite',
            name='classes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='classes.Class'),
        ),
        migrations.RemoveField(
            model_name='prerequisite',
            name='possibleClasses',
        ),
        migrations.AddField(
            model_name='prerequisite',
            name='possibleClasses',
            field=models.ManyToManyField(related_name='possibleClasses', to='classes.Class'),
        ),
    ]
