# Generated by Django 2.2.6 on 2019-11-24 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0007_auto_20191124_1831'),
    ]

    operations = [
        migrations.RenameField(
            model_name='degreesection',
            old_name='auditId',
            new_name='audit',
        ),
        migrations.RenameField(
            model_name='prerequisite',
            old_name='auditId',
            new_name='audit',
        ),
    ]
