# Generated by Django 2.2.6 on 2019-11-24 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0008_auto_20191124_1856'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audit',
            old_name='userId',
            new_name='user',
        ),
    ]
